version: '3.8'

services:
  axol_web:
    container_name: axol_web
    build:
      context: .
    restart: always
    # command: sh -c "npm run dev & php artisan serve --host=0.0.0.0"
    volumes:
      - ".:/app/axol_web:cached" # Volumen para actualizar el código en tiempo real
      - /app/axol_web/node_modules
    ports:
      - "8000:8000"
      - "5173:5173"
    networks:
      - axol-network
    env_file:
      - .env
    command: sh -c "npm run dev & php artisan serve --host=0.0.0.0"

networks:
  axol-network:
    driver: bridge